# Generated by Django 2.2.6 on 2019-10-31 13:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=63, verbose_name='プロジェクト名')),
                ('melody_data', jsonfield.fields.JSONField(verbose_name='メロディデータ')),
                ('artist', models.CharField(max_length=31, verbose_name='アーティスト')),
                ('key', models.CharField(max_length=7, verbose_name='キー')),
                ('beat_pattern', models.CharField(max_length=1, verbose_name='ビートパターン')),
                ('chord_prog', models.CharField(max_length=63, verbose_name='コード進行')),
                ('bpm', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)], verbose_name='BPM')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'プロジェクト',
                'verbose_name_plural': 'プロジェクト',
                'db_table': 'project',
                'ordering': ['created_at'],
                'unique_together': {('project_name', 'author')},
            },
        ),
    ]
