# Generated by Django 2.2.6 on 2019-11-01 08:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='melody_data',
            field=jsonfield.fields.JSONField(null=True, verbose_name='メロディデータ'),
        ),
    ]
