# Generated by Django 2.2.6 on 2019-11-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0002_auto_20191101_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='beat_pattern',
            new_name='rhythm_pattern',
        ),
    ]
