# Generated by Django 2.2.6 on 2019-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0003_auto_20191102_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='artist',
            field=models.CharField(max_length=32, verbose_name='アーティスト'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chord_prog',
            field=models.CharField(max_length=64, verbose_name='コード進行'),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=8, verbose_name='キー'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=64, verbose_name='プロジェクト名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rhythm_pattern',
            field=models.CharField(max_length=1, verbose_name='リズムパターン'),
        ),
    ]
