# Generated by Django 2.2.6 on 2019-12-10 06:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0004_auto_20191102_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='effect_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='エフェクトデータ'),
        ),
        migrations.AddField(
            model_name='project',
            name='pan_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='パンデータ'),
        ),
        migrations.AddField(
            model_name='project',
            name='volume_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='ボリュームデータ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='melody_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='メロディデータ'),
        ),
    ]
