# Generated by Django 2.2.6 on 2019-12-12 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0005_auto_20191210_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chord_inst_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='コード楽器番号'),
        ),
    ]
