# Generated by Django 2.2.6 on 2020-02-06 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0006_project_chord_inst_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='melody_inst_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='メロディ楽器番号'),
        ),
    ]
